# Generated by Django 5.0.6 on 2024-07-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['date']},
        ),
    ]
