# Generated by Django 4.2.6 on 2024-09-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hotel_owner',
            field=models.BooleanField(default=False),
        ),
    ]
