# Generated by Django 4.2.6 on 2024-09-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0010_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_hotel', to=settings.AUTH_USER_MODEL),
        ),
    ]
